package com.idothestamping.lab11.songr.SongrController;

import com.idothestamping.lab11.songr.Song;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import com.idothestamping.lab11.songr.Album;
import com.idothestamping.lab11.songr.AlbumRepo;
import org.springframework.web.servlet.view.RedirectView;

@Controller
public class AlbumController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    AlbumRepo AlbumRepo;
    @Autowired
    com.idothestamping.lab11.songr.SongRepo SongRepo;

    @GetMapping("/album")
    public String getAllAlbum(Model m) {
        Iterable<Album> albums = AlbumRepo.findAll();
        m.addAttribute("allAlbums", albums);
        return "index";
    }

    @GetMapping("/album/{id}")
    public String getOneAlbumDetail(@PathVariable Long id, Model m){
        Album a = AlbumRepo.findById(id).get();
        Iterable<Song> songs = SongRepo.findAll();
        m.addAttribute("allSongs", songs);
        m.addAttribute("allAlbums",a);
        return "song";
    }

    @PostMapping("/album/{id}")
    public RedirectView addAlbum(String title, String artist, Long songCount, Long length, String imageUrl) {
        Album userInput = new Album(title, artist, songCount, length, imageUrl);
        AlbumRepo.save(userInput);
        return new RedirectView("/album");
    }
}