package com.idothestamping.lab11.songr.SongrController;

import com.idothestamping.lab11.songr.Song;
import com.idothestamping.lab11.songr.AlbumRepo;
import com.idothestamping.lab11.songr.SongRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.view.RedirectView;

@Controller
public class SongController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    com.idothestamping.lab11.songr.SongRepo SongRepo;
    @Autowired
    AlbumRepo AlbumRepo;


    @GetMapping("/song")
    public String getAllSong(Model m) {
        Iterable<Song> songs = SongRepo.findAll();
        m.addAttribute("allSongs", songs);
        return "song";
    }

    @RequestMapping(value="/song/{id}", method = RequestMethod.GET)
    public String getAlbumSongs(@PathVariable Long id, Model m) {
        // .get to get value inside of optional
        Song songs = SongRepo.findById(id).get();
        m.addAttribute("allSongs", songs);
        return "song";
    }
    @PostMapping("/song/{id}")
    public String updateSongs(@PathVariable Long id, @RequestParam Long length, @RequestParam Long trackNumber) {
        Song songs = SongRepo.findById(id).get();
        songs.length = length;
        songs.trackNumber = trackNumber;
        SongRepo.save(songs);
        System.out.println(songs.length);
        return "redirect:/song";
    }

//    @PostMapping("/song/{id}")
//    public RedirectView addSongs(String title, Long length, Long trackNumber, String from_album) {
//        Song userInput = new Song(title, length, trackNumber, from_album);
//        SongRepo.save(userInput);
//        return new RedirectView("/song");
//    }

//    @PostMapping("/song")
//    public RedirectView addSongs(String title, int length, int trackNumber, AlbumRepo title) {
//        Song userInput = new Song(title, length, trackNumber, from_album);
//        SongRepo.save(userInput);
//        return new RedirectView("/song");
//    }
}
